/* Lógico_1: */

CREATE TABLE CLIENTES (
    Cod_Cliente INT PRIMARY KEY,
    Nome CHAR(30),
    Sobrenome CHAR(30),
    Inicial CHAR(1),
    DDD CHAR(5),
    Telefone VARCHAR(9),
    Saldo FLOAT
);

CREATE TABLE FATURAS (
    Num_Fatura INT PRIMARY KEY,
    Data_Fatura DATE,
    FK_CLIENTES_Cod_Cliente INT
);

CREATE TABLE LINHAS (
    Num_Linha INT PRIMARY KEY,
    Unidade INT,
    Valor FLOAT,
    FK_FATURAS_Num_Fatura INT,
    FK_PRODUTOS_Cod_Produto INT
);

CREATE TABLE PRODUTOS (
    Cod_Produto INT PRIMARY KEY,
    Descricao VARCHAR(200),
    Data_Compra DATE,
    Quantidade INT,
    Valor FLOAT,
    Descontos FLOAT,
    FK_FORNECEDORES_Cod_Fornecedor INT
);

CREATE TABLE FORNECEDORES (
    Cod_Fornecedor INT PRIMARY KEY,
    Nome CHAR(30),
    Contato VARCHAR(200),
    DDD CHAR(5),
    Telefone VARCHAR(9),
    Estado CHAR(2),
    Cidade CHAR(50)
);
 
ALTER TABLE FATURAS ADD CONSTRAINT FK_FATURAS_2
    FOREIGN KEY (FK_CLIENTES_Cod_Cliente)
    REFERENCES CLIENTES (Cod_Cliente)
    ON DELETE CASCADE;
 
ALTER TABLE LINHAS ADD CONSTRAINT FK_LINHAS_2
    FOREIGN KEY (FK_FATURAS_Num_Fatura)
    REFERENCES FATURAS (Num_Fatura)
    ON DELETE RESTRICT;
 
ALTER TABLE LINHAS ADD CONSTRAINT FK_LINHAS_3
    FOREIGN KEY (FK_PRODUTOS_Cod_Produto)
    REFERENCES PRODUTOS (Cod_Produto)
    ON DELETE CASCADE;
 
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_2
    FOREIGN KEY (FK_FORNECEDORES_Cod_Fornecedor)
    REFERENCES FORNECEDORES (Cod_Fornecedor)
    ON DELETE CASCADE;
